spring:
  datasource:
    url: 'jdbc:h2:mem:GitUserDB'
    driverClassName: 'org.h2.Driver'
    username: 'user'
    password: 'user'
  mvc:
    pathmatch:
      matching-strategy: 'ant_path_matcher'


