spring:
  datasource:
    url: 'jdbc:h2:mem:GitUserDBTest'
    driverClassName: 'org.h2.Driver'
    username: 'user'
    password: 'user'
    path: '/console'
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: 'ant_path_matcher'
    message-codes-resolver-format: postfix_error_code
server:
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: on

